Typescript Support Added
RDoll-Repo/To-Do-API pull request #1
Opened 2022-01-11 21:42 UTC by RDoll-Repo

This is a practice PR.

2022-01-12 15:26 UTC, lawhorkl requested changes
First comment is that we should not check in node modules to the project in git. We should add the node modules folder to the git ignore file. In general we only commit files that we ourselves wrote. Any libraries or other packages are not included in the repo.

2022-01-12 17:43 UTC, RDoll-Repo commented
node_modules has been added to gitignore. Package, package lock, and tsconfig all had to be manually edited.

2022-01-14 20:55 UTC, lawhorkl commented on package.json
> +  },
We could use something called `nodemon` here to automatically watch for changes in our TS files and then run the compiler when it changes

2022-01-14 21:00 UTC, lawhorkl approved these changes

2022-01-14 21:00 UTC, merged