Api prototype
RDoll-Repo/To-Do-API pull request #3
Opened 2022-01-24 16:32 UTC by RDoll-Repo

copied into a fresh branch off main as requested.

2022-01-24 18:41 UTC, lawhorkl requested changes
My only review so far is this:

How do you plan to scale the application in terms of folder structure? In real-world APIs your API program could have thousands of different endpoints/files so where do all those definitions go? Inside of index?

I would like to see a structured project with all TS files grouped together like
`routes/`, `services/`, etc.

2022-01-25 20:13 UTC, RDoll-Repo commented
Endpoints have gone into their own file. One generic function handles all routes

2022-01-28 15:16 UTC, lawhorkl requested changes

2022-01-28 15:16 UTC, lawhorkl commented on index.ts
> +})
changing `unhandledRejection` probably makes this code block not work

2022-01-28 15:16 UTC, lawhorkl commented on src/endpoints/todoEndpoints.ts
> +            h: any) =>
Part of the advantage of using typescript is being able to strongly type variables. Hapi has decent typescript support you need to do some research regarding using Hapi TypeScript types

2022-01-31 21:00 UTC, RDoll-Repo commented
"any" typing has been replaced with specific typing.

2022-01-31 21:05 UTC, lawhorkl approved these changes

2022-01-31 21:05 UTC, merged